<?php

namespace Drupal\commerce_recurring;

use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Represents a single billing cycle.
 *
 * Billing cycles are generated by billing schedule plugins.
 *
 * @see \Drupal\commerce_recurring\Plugin\Commerce\BillingSchedule\BillingScheduleInterface
 */
final class BillingCycle {

  /**
   * The time the billing cycle starts.
   *
   * @var \Drupal\Core\Datetime\DrupalDateTime
   */
  protected $startDate;

  /**
   * The time the billing cycle ends.
   *
   * @var \Drupal\Core\Datetime\DrupalDateTime
   */
  protected $endDate;

  /**
   * BillingCycle constructor.
   *
   * @param \Drupal\Core\Datetime\DrupalDateTime $start_date
   *   The start time.
   * @param \Drupal\Core\Datetime\DrupalDateTime $end_date
   *   The end time.
   */
  public function __construct(DrupalDateTime $start_date, DrupalDateTime $end_date) {
    $this->startDate = $start_date;
    $this->endDate = $end_date;
  }

  /**
   * Gets the start date.
   *
   * @return \Drupal\Core\Datetime\DrupalDateTime
   *   The start date.
   */
  public function getStartDate() {
    return $this->startDate;
  }

  /**
   * Gets the end date.
   *
   * @return \Drupal\Core\Datetime\DrupalDateTime
   *   The end date.
   */
  public function getEndDate() {
    return $this->endDate;
  }

}
